gmql_service/gmql/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from gmql import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^queries/$', views.queries, name='queries'),
                       url(r'^queries/(?P<filter>\w+)/$', views.queries, name='queries'),
                       url(r'^custom/$', views.custom, name='custom'),
                       url(r'^about/$', views.about, name='about'),
                       url(r'^documentation/$', views.documentation, name='documentation'),
                       url(r'^licence/$', views.licence, name='licence'),
                       url(r'^metadata/(?P<meta_name>\w+)/$', views.metadata, name='metadata'),
                       url(r'^documentation/full_doc$', views.full_doc, name='full_doc'),
                       url(r'^query/(?P<query_id>\d+)/$', views.query, name='query'),
                       url(r'^query/(?P<query_id>\d+)/delete/$', views.delete_query, name='delete_query'),
                       url(r'^task/(?P<pk>\d+)/$', views.TaskView.as_view(), name='task'),
                       url(r'^task/(?P<pk>\d+)/download/(?P<file_id>\d+)/$', views.file_download, name='file_download'),

)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

gmql_service/gmql_service/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views import defaults
import gmql
from gmql.rest import QueryList, QueryDetails, TaskList, TaskDetails, gmql_api


urlpatterns = patterns('',
    url(r'^', include('gmql.urls', namespace='gmql')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('allauth.urls')),


    # prevent the extra are-you-sure-you-want-to-logout step on logout
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('gmql:index')}),

    url(r'^accounts/profile/', gmql.views.profile, name='profile'),

    # block pages
    url(r"^inactive/$", defaults.page_not_found, name="account_inactive"),
    url(r"^email/$", defaults.page_not_found, name="account_email"),
    url(r"^confirm-email/$", defaults.page_not_found,
        name="account_email_verification_sent"),
    url(r"^confirm-email/(?P<key>\w+)/$", defaults.page_not_found,
        name="account_confirm_email"),
    # Handle old redirects
    url(r"^confirm_email/(?P<key>\w+)/$",
        defaults.page_not_found),

    (r'^selectable/', include('selectable.urls')),

    url(r'^rest/$', gmql_api, name='rest'),
    url(r'^rest/queries/$', QueryList.as_view(), name='query-list'),
    url(r'^rest/queries/(?P<pk>[0-9]+)/$', QueryDetails.as_view(), name='query-detail'),
    url(r'^rest/tasks/$', TaskList.as_view(), name='task-list'),
    url(r'^rest/tasks/(?P<pk>[0-9]+)/$', TaskDetails.as_view(), name='task-detail'),
    url(r'^rest/api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    url(r'^forum/', include('pybb.urls', namespace='pybb')),
)

gmql_service/gmql/views.py
from django.core.exceptions import SuspiciousFileOperation
from django.core.files.storage import FileSystemStorage
from gmql.utils.SpecialMeta import SpecialMeta
from gmql.utils.TagsRegistry import Tags
import os
from allauth.account.adapter import DefaultAccountAdapter
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.conf import settings

from gmql.models import Query, Parameter, CustomQueryModelForm, ParametersFormset, \
    generate_forms_list, Task, GMQLFile, QuerySearchForm, add_default_files, Chart
from gmql.utils import gmql_parser
from gmql.tasks import process_task


def index(request):
    if request.user.is_authenticated():
        return redirect(reverse('gmql:queries'))
    return render(request, 'gmql/index.html')


def about(request):
    return render(request, 'gmql/about.html')

def documentation(request):
    return render(request, 'gmql/documentation.html')


def get_pdf_file_response(file_name):
    with open(os.path.join(settings.MEDIA_ROOT, 'docs', file_name), 'r') as pdf:
        response = HttpResponse(pdf.read(),content_type='application/pdf')
        response['Content-Disposition'] = 'filename=%s' % file_name
        return response


def get_txt_file_response(file_name):
    with open(os.path.join(settings.MEDIA_ROOT, 'dicts', file_name), 'r') as pdf:
        response = HttpResponse(pdf.read(),content_type='text/plain')
        response['Content-Disposition'] = 'filename=%s' % file_name
        return response



def full_doc(request):
    return get_pdf_file_response('GMQL_Complete_Documentation.pdf')


def licence(request):
    return get_pdf_file_response('gpl-2.0.pdf')

def metadata(request, meta_name):
    res_meta = None
    metas = SpecialMeta.special_metas
    for m in metas:
        if m.name == meta_name:
            res_meta = m
            break
    if not res_meta:
        raise Http404('No %s metadata found.' % meta_name)

    return get_txt_file_response(res_meta.file_name)


def queries(request, filter=None):
    mostly_used_query_list = Query.objects.globals().tags(filter).order_by('-used')
    custom_query_list = None
    if request.user.is_authenticated():
        custom_query_list = Query.objects.customs(user=request.user).tags(filter).order_by('-used')

    search_form = QuerySearchForm(request.POST or None)
    if search_form.is_valid():
        mostly_used_query_list = mostly_used_query_list.search(search_form.cleaned_data['search_value'])
        if custom_query_list:
            custom_query_list = custom_query_list.search(search_form.cleaned_data['search_value'])


    context = {'mostly_used_query_list': mostly_used_query_list,
                'custom_query_list': custom_query_list,
                'tag_categories' : Tags.tags_dict(),
                'search_form' : search_form,
                }

    return render(request, 'gmql/queries.html', context)

@login_required()
def profile(request):
    context = {}
    context['custom_query_list'] = Query.objects.customs(user=request.user).order_by('-used')
    context['task_list'] = Task.objects.filter(user=request.user)
    return render(request, 'gmql/profile.html', context)


@login_required()
def delete_query(request, query_id):
    query = get_object_or_404(Query, pk=query_id)
    if query.user == request.user and not query.is_global:
        query.delete()
    return redirect(reverse('gmql:queries'))


# TODO: demo user
@login_required()
def query(request, query_id):
    query = get_object_or_404(Query, pk=query_id)

    if not request.user.is_superuser and query.user and not query.is_global and query.user != request.user:
        raise Http404

    parameters = Parameter.objects.filter(query=query_id)
    parameters_data = list(parameters.values())
    formset = generate_forms_list(parameters_data)

    if request.method == 'POST':
        if 'run' in request.POST or 'try' in request.POST:
            formset = generate_forms_list(parameters_data, request.POST, request.FILES)
            if 'try' in request.POST:
                formset = generate_forms_list(parameters_data, request.POST, request.FILES, use_default=True)
            if all([form.is_valid() for form in formset]):
                parameters_dict = {}
                [parameters_dict.update(f.get_parameters_dict(parameters_data)) for f in formset]
                task = Task(query_id=query_id, user_id=request.user.id)
                task.set_parameters(parameters_dict)
                task.set_status_msg(Task.PREPARED)
                files = request.FILES
                if 'try' in request.POST:
                    files = add_default_files(parameters_data, request.FILES)
                result = process_task.delay(task, files)
                return redirect(reverse('gmql:task', args=[task.id]))
        elif 'see' in request.POST:
            formset = generate_forms_list(parameters_data, request.POST, request.FILES, use_default=True)

        elif 'check' in request.POST:
            formset = generate_forms_list(parameters_data, request.POST, request.FILES)
            if all([form.is_valid() for form in formset]):
                parameters_dict = {}
                [parameters_dict.update(f.get_parameters_dict(parameters_data)) for f in formset]
                statements = query.extract_selection_statements(parameters_dict)
                context = {'query': query,
                            'formset': formset,
                            'select_data': None,
                           'hint_statements': {'checked':True, 'statements': statements}}
                return render(request, 'gmql/query.html', context)


    context = {'query': query,
               'formset': formset}
    return render(request, 'gmql/query.html', context)


class TaskView(DetailView):
    model = Task
    template_name = 'gmql/task.html'

    def get_object(self, queryset=None):
        obj = super(TaskView, self).get_object()
        if not self.request.user.is_superuser and obj.user is not None and obj.user != self.request.user:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super(TaskView, self).get_context_data(**kwargs)
        context['file_list'] = GMQLFile.objects.filter(task=self.object.pk, file_type=GMQLFile.DOWNLOAD)

        #TODO add for other genomes
        if self.object.query.is_hg19():
            context['igb_files'] = GMQLFile.objects.filter(task=self.object.pk, file_type=GMQLFile.BROWSE, label='IGB')

        context['charts'] = Chart.objects.filter(task=self.object).order_by('name')
        #context['charts'] = [
        #    Chart(task=self.object, name='chast_name', archive_name='arch_name', pk=1),
        #                     ]

        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TaskView, self).dispatch(*args, **kwargs)


@login_required()
def file_download(request, pk, file_id):
    gmqlfile = GMQLFile.objects.get(id=file_id)
    if not request.user.is_superuser and gmqlfile.task.user and gmqlfile.task.user != request.user:
        raise Http404
    response = HttpResponse()
    response['Content-Disposition'] = "attachment; filename=%s" % (gmqlfile)
    response['X-Accel-Redirect'] = settings.MEDIA_URL + gmqlfile.download_path
    return response


@login_required()
def custom(request):
    if request.method == 'POST':
        if 'submit_example' in request.POST:
            print request.POST
            example_query = Query()
            example_query.set_example_data()
            custom_form = CustomQueryModelForm(prefix='query', instance=example_query)
        else:
            custom_form = CustomQueryModelForm(request.POST, prefix='query')
        parameters_form = None
        context = {'custom_form': custom_form}

        if 'submit_parameters' in request.POST:
            # generate parameters
            if custom_form.is_valid():
                parameters = gmql_parser.parse_gqml_parameters(custom_form.cleaned_data['query'])
                if len(parameters) != 0:
                    #parameters_form
                    initials = [{'name': par, 'description': 'Description of ' + par} for par in parameters]
                    parameters_form = ParametersFormset(initial=initials, )

        elif 'submit_create' in request.POST:
            custom_form = CustomQueryModelForm(request.POST, prefix='query')
            parameters_form = ParametersFormset(request.POST)
            if custom_form.is_valid() and parameters_form.is_valid():
                new_query = Query(**custom_form.cleaned_data)
                new_query.user = request.user
                new_query.save()
                for parameter_form in parameters_form:
                    new_parameter = Parameter(**parameter_form.cleaned_data)
                    new_parameter.query = new_query
                    new_parameter.save()
                return redirect(reverse('gmql:query', args=[new_query.id]))
    else:
        custom_form = CustomQueryModelForm(prefix='query')
        parameters_form = None

    context = {'custom_form': custom_form,
               'special_metas': SpecialMeta.special_metas}
    if parameters_form is not None:
        context['parameters_form'] = parameters_form
    return render(request, 'gmql/custom_form.html', context)


class AccountAdapter(DefaultAccountAdapter):
    def get_login_redirect_url(self, request):
        return reverse('gmql:queries')



#HACK to avoid exeptions on deleting files with bad path
class FileStorage(FileSystemStorage):
    def exists(self, name):
        try:
            return super(FileStorage, self).exists(name)
        except SuspiciousFileOperation:
            return False

gmql_service/gmql/templates/gmql/base.html
{% load staticfiles %}
<html>
<head>

    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GMQL Service</title>


    <link href="{% static 'gmql/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'gmql/bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link href="{% static 'gmql/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link  href="{% static 'gmql/images/favicon.ico' %}" rel="icon" type="image/x-icon" />

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        body {
            padding-top: 50px; /* 50px to make the container go all the way to the bottom of the topbar */
        }
    </style>

    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    <script src="{% static 'gmql/bootstrap/js/bootstrap.js' %}" type="text/javascript"></script>
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
        $(function () {
            {% block jquery %}
            {% endblock %}
        });
    </script>
</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'gmql:index' %}">GMQL Service</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'gmql:queries' %}">Tools</a></li>
                <li><a href="{% url 'gmql:custom' %}">Custom query</a></li>
                <li><a href="{% url 'gmql:documentation' %}">Documentation</a></li>
                <li><a href="{% url 'pybb:index' %}">Forum</a></li>
                <li><a href="{% url 'rest' %}">API</a></li>
                <li><a href="{% url 'gmql:about' %}">About</a></li>
                {% if user.is_authenticated and user.is_staff%}
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><img class="img-circle" src="{{ user.image }}"/></li>
                    <li><a href="{% url 'profile' %}" >{{ user.email }}</a></li>
                {% else %}
                    <li><a href="{% url 'account_login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</div>


{% block gmql_content %}
{% endblock %}




<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'gmql/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'gmql/bootstrap/js/docs.min.js' %}"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59251542-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

gmql_service/gmql/templates/gmql/custom_form.html
{% extends "gmql/base.html" %}
{% load bootstrap staticfiles%}

{% block extrahead %}
    <script src="{% static 'gmql/codemirror/lib/codemirror.js' %}"></script>
    <link rel="stylesheet" href="{% static 'gmql/codemirror/lib/codemirror.css' %}">
    <script src="{% static 'gmql/codemirror/mode/gmql/gmql.js' %}"></script>
    <link href="{{ STATIC_URL }}gmql/bootstrap/css/queries.css" rel="stylesheet">
{% endblock %}

{% block gmql_content %}

    <div class="container">
        <form action="{% url 'gmql:custom' %}" method="post">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Custom query
                        <button type="submit" class="btn btn-info btn-sm" name="submit_example"> Hello, world</button>
                    </h3>
                </div>
                <div class="panel-body">
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    {% csrf_token %}
                    {{ custom_form|bootstrap }}
                {% if special_metas %}
                    <div class="bs-callout bs-callout-info">
                        <h4>Available Datasets</h4>
                        The datasets can be used in the queries. Each dataset has associated metadata parameters, click on a dataset to see all its parameters.
                        <ul>
                        {% for sm in special_metas %}
                            <li><a href="{% url 'gmql:metadata' sm.name %}">{{ sm.name }}</a></li>
                        {% endfor %}
                        </ul>
                        </div>
                {% endif %}
                    <button type="submit" class="btn btn-primary" name="submit_parameters">Generate parameters</button>
                </div>
            </div>

            {% if parameters_form %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Parameters</h3>
                    </div>
                    <div class="panel-body">
                        {{ parameters_form.management_form }}
                        <table id="formset" class="table">

                            {% for form in parameters_form %}
                                {% if forloop.first %}
                                    <thead>
                                    <tr>
                                        {% for field in form.visible_fields %}
                                            <th>
                                                {% if field.label != 'Name' %}
                                                    <span class="glyphicon glyphicon-ok"></span>
                                                {% endif %}
                                                {{ field.label|capfirst }}</th>
                                        {% endfor %}
                                    </tr>
                                    </thead>
                                {% endif %}
                                <tr class="{% cycle row1,row2 %}">
                                    {% for field in form.visible_fields %}
                                        <td>
                                            {# Include the hidden fields in the form #}
                                            {% if forloop.first %}
                                                {% for hidden in form.hidden_fields %}
                                                    {{ hidden }}
                                                {% endfor %}
                                            {% endif %}

                                            {% if field.label != 'Name' %}

                                                {{ field }}

                                            {% else %}
                                                {# to include data in the POST #}
                                                {{ field.as_hidden }}

                                                {{ field.value }}
                                            {% endif %}
                                            {{ field.errors.as_ul }}
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                    </div>

                </div>
                <button type="submit" class="btn btn-primary btn-lg" name="submit_create"><span
                        class="glyphicon glyphicon-ok"></span> Create query
                </button>
            {% endif %}
        </form>

    </div>

{% endblock %}

gmql_service/gmql/templates/gmql/index.html
{% extends "gmql/base.html" %}
{% load staticfiles %}

{% block extrahead %}
    <link href="{% static 'gmql/bootstrap/css/carousel.css' %}" rel="stylesheet">
{% endblock %}

{% block gmql_content %}
    <!-- Carousel
        ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="item active">
                <img src="{% static 'gmql/images/example2.jpg' %}" alt="First slide">

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Bioinformatics queries.</h1>

                        <p>Genomic operations with immidiate response.</p>

                        {% if not user.is_authenticated %}
                            <p><a class="btn btn-lg btn-primary" href="{% url 'account_login' %}" role="button">Log in</a></p>
                        {% else %}
                            <p><a class="btn btn-lg btn-primary" href="{% url 'gmql:queries' %}" role="button">Tools</a></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="{% static 'gmql/images/example3.jpg' %}" alt="Second slide">

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Tools.</h1>

                        <p>Easy to use: select a query, set parameters and get the result.</p>

                        <p><a class="btn btn-lg btn-primary" href="{% url 'gmql:queries' %}" role="button">Tools</a></p>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="{% static 'gmql/images/example5.jpg' %}" alt="Third slide">

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Custom query.</h1>

                        <p>Create a custom service with parameters.</p>

                        <p><a class="btn btn-lg btn-primary" href="{% url 'gmql:custom' %}" role="button">Create</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span
                class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span
                class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->
    <!-- Marketing messaging and featurettes
      ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
        <!-- START THE FEATURETTES -->

        <div class="row featurette">
            <div class="col-md-5">
                <img class="featurette-image img-responsive" src="{% static 'gmql/images/plate.png' %}"
                     alt="Generic placeholder image">
            </div>

            <div class="col-md-7">
                <h2 class="featurette-heading">Bioinformatics services: <span class="text-muted">data retrieving, filtering, transformation.</span>
                </h2>

                <p class="lead">Point-and-click services to process your data right away. Intersect your own data with public collections.</p>
            </div>
        </div>


        <hr class="featurette-divider">


        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">Performance. <span class="text-muted">For rapid data processing.</span>
                </h2>

                <p class="lead">Each task is performed on a high-performance cloud-based server to rabidly query biodata collections.</p>
            </div>
            <div class="col-md-5">
                <img class="featurette-image img-responsive" src="{% static 'gmql/images/server.jpg' %}"
                     alt="Generic placeholder image">
            </div>
        </div>


        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-5">
                <img class="featurette-image img-responsive" src="{% static 'gmql/images/gmql_logo.png' %}"
                     alt="Generic placeholder image">
            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading">Flexibility. <span class="text-muted">For new services.</span>
                </h2>

                <p class="lead">Each service is a parametrised query in GenoMetric Query Language. Add a new query - get a new service.</p>
            </div>

        </div>


        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-3">
                <img class="img-circle" src="{% static 'gmql/images/genomics.png' %}" alt="Generic placeholder image"
                     style="width: 140px; height: 140px;">

                <h2>Genomic regions</h2>

                <p>Basic operations on genomic regions: filtering, sorting, intersection</p>
            </div>
            <!-- /.col-lg-3 -->
            <div class="col-lg-3">
                <img class="img-circle" src="{% static 'gmql/images/encode.png' %}" alt="Generic placeholder image"
                     style="width: 140px; height: 140px;">

                <h2>ENCODE Data</h2>

                <p>Retrieving ENCODE samples and intersecting with your data</p>
            </div>
            <div class="col-lg-3">
                <img class="img-circle" src="{% static 'gmql/images/epigenome.jpg' %}" alt="Generic placeholder image"
                     style="width: 140px; height: 140px;">

                <h2>Epigenome Roadmap Data</h2>

                <p>Introduces epignomic data to research</p>
            </div>
            <!-- /.col-lg-3 -->
        </div>
        <!-- /.row -->

        <hr class="featurette-divider">


        <!-- FOOTER -->
        <footer>
            <p class="pull-right"><a href="{% url 'gmql:index' %}">Back to top</a></p>

            <p>&copy; {% now "Y" %} PoliMi. &middot; <a href="{% url 'gmql:licence' %}">License</a>
        </footer>

    </div><!-- /.container -->
{% endblock %}

gmql_service/gmql/templates/gmql/task.html
{% extends "gmql/task_graphs.html" %}

{% load gmql_tags %}

{% block task_result %}
    {% for item in file_list|partition_label %}
        {% if forloop.first %}
            <table class="table">
            <thead>
            <tr>
                <td>

                </td>
            {% for label in item.labels %}
               <td>
                    {{ label }}
               </td>
            {% endfor %}
            </tr>
            </thead>
        {% endif %}
        <tr>
           <td>
                {{ item.name }}
           </td>
            {% for file in item.files %}
               <td>
                    <a href="{% url 'gmql:file_download' task.id file.id %}">Download</a>
               </td>
            {% endfor %}
        </tr>

        {% if forloop.last %}
            </table>
        {% endif %}
    {% endfor %}
{% endblock %}

{% block task_browser %}
    {% for file in igb_files %}
        {% if forloop.first %}
            <p class="lead">
                <i><a href="http://bioviz.org/igb/index.html">IGB</a> Visualization</i>. Please, launch <a href="http://bioviz.org/igb/index.html">IGB</a> on your computer and then click a link below.
            </p>
            <ul>
        {% endif %}
            <li>
                <a href="{{ file.igb_link }}">Open {{ file }} in IGB</a>
            </li>
        {% if forloop.last %}
            </ul>
        {% endif %}
    {% endfor %}
{% endblock %}